version: '3'

services:

  example-app:  
    build:
      context: src/python/example-app/ 
      dockerfile: Dockerfile
      
    ports:
      - "5000:5000"

  mysql-central-server:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=products_stock
      - MYSQL_USER=athemes_user
      - MYSQL_PASSWORD=athemes_password
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

  central-server:
    build: ./central_server
    command: sh -c "
                 wait-for-it mysql-central-server:3306 &&
                 python manage.py migrate &&
                 python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./central_server:/code
    ports:
      - "8000:8000"
    env_file:
      - ./central_server/.env
    depends_on:
      - mysql-central-server

